[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./chainlink-functions" }]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 10000

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@solbase/=lib/solbase/src/",
    "@solmate/=lib/solmate/src/",
    "@chainlink/contracts/=lib/chainlink/contracts/src/v0.8/",
    "@chainlink/contracts-ccip/=lib/chainlink/contracts/src/v0.8/ccip/",
    "@chainlink/functions/=lib/chainlink/contracts/src/v0.8/functions/",
    "@chainlink/data-feeds/=lib/chainlink/contracts/src/v0.8/data-feeds/"
]

[fmt]
tab_width = 4
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
number_underscore = "thousands"

# Foundry configuration
[fuzz]
runs = 256

[invariant]
runs = 256
depth = 15
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options